# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passW0RD
      MYSQL_DATABASE: 'djask'
    volumes:
      - ~/mysql-data:/var/lib/mysql

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
