# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passW0RD
      MYSQL_DATABASE: 'djask'
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - ~/mysql-data:/var/lib/mysql

  web:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      PROD: "1"
    volumes:
      - .:/usr/src/djask
    command: ["./wait-for-it.sh", "db:3306", "--", "./ep.sh"]
